allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - framer-motion@13.3.0
  - lucide-react@1.46.0
  - motion-dom@13.3.0
  - motion-utils@13.3.0
  - motion@13.3.0
onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - sharp
  - unrs-resolver
